name: actions-ws
on:
  push:
    branches:
      - master
  
jobs:

  versioning:
    name: "Release"
    permissions:
      contents: write
    uses: ProdigySim/action-versioning-workflow/.github/workflows/action_versioning.yml@v1
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      -
        name: docker build
        uses: docker/setup-buildx-action@v3
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: docker push
        uses: docker/build-push-action@v5
        env:
          VERSION_ID: ${{  github.ref_name }}
        with:
          context: .
          push: true
          tags: amosops/actions-ws:${{  github.ref_name }}
