name: actions-ws
on:
  push:
    branches:
      - master
  
jobs:

  versioning:
    name: "Release"
    permissions:
      contents: write
    uses: ProdigySim/action-versioning-workflow/.github/workflows/action_versioning.yml@v1
    
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      - 
        uses: olegtarasov/get-tag@v2.1.3
        name: Get the tag
        id: tagName
        with:
          tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      -
        name: docker build
        uses: docker/setup-buildx-action@v3
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: docker push
        uses: docker/build-push-action@v5
        env:
          VERSION_ID: ${{ steps.tagName.outputs.tag }}
        with:
          context: .
          push: true
          tags: amosops/actions-ws:${{ steps.tagName.outputs.tag }}
          build-args: |
            VERSION_ID=${{ env.VERSION_ID }}
