name: actions-ws
on:
  push:
    branches:
      - master
  
jobs:

  versioning:
    name: "Release"
    permissions:
      contents: write
    uses: ProdigySim/action-versioning-workflow/.github/workflows/action_versioning.yml@v1
    
  docker-build:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: docker build
        uses: docker/setup-buildx-action@v3
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get tags
        id: get-tags
        run: |
          echo "VERSION_ID=$(git fetch --tags -f && git tag -l | sort -V | awk 'END{print}')" >> $GITHUB_ENV
      -
        name: docker push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: amosops/actions-ws:${{ env.VERSION_ID }}
          build-args: |
            VERSION_ID=${{ env.VERSION_ID }}
      -
        name: pull and run
        run: |
          sudo docker system prune -f
          sudo docker pull amosops/actions-ws:${{ env.VERSION_ID }}
          sudo docker run --name deploy-actions-ws -d amosops/actions-ws:${{ env.VERSION_ID }}
