name: actions-ws
on:
  push:
    branches:
      - master
env:
  VERSION_ID: ${{ github.event.release.tag_name }}
  
jobs:

  versioning:
    name: "Release"
    permissions:
      contents: write
    uses: ProdigySim/action-versioning-workflow/.github/workflows/action_versioning.yml@v1
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: docker build
        uses: docker/setup-buildx-action@v3
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: docker push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: amosops/actions-ws:${{ env.VERSION.ID }}
