name: actions-ws
on:
  push:
    branches:
      - master
  
jobs:

  versioning:
    name: "Release"
    permissions:
      contents: write
    uses: ProdigySim/action-versioning-workflow/.github/workflows/action_versioning.yml@v1
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: true # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not found
      - 
        name: Use tag
        run: echo ${{steps.tag.outputs.tag}
      -
        name: docker build
        uses: docker/setup-buildx-action@v3
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: docker push
        uses: docker/build-push-action@v5
        env:
          VERSION_ID: ${{steps.tag.outputs.tag}}
        with:
          context: .
          push: true
          tags: amosops/actions-ws:${{steps.tag.outputs.tag}}
          build-args: |
            VERSION_ID=${{ env.VERSION_ID }}
