name: actions-ws
on:
  push:
    branches:
      - master
  
jobs:

  versioning:
    name: "Release"
    permissions:
      contents: write
    uses: ProdigySim/action-versioning-workflow/.github/workflows/action_versioning.yml@v1
    
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: docker build
        uses: docker/setup-buildx-action@v3
      -
        name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get tags
        id: get-tags
        run: echo $(git fetch --tags -f && git tag | awk 'END{print}') >> $GITHUB_OUTPUT
      -
        name: docker push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: amosops/actions-ws:${{ steps.get-tags.output }}
          build-args: |
            VERSION_ID=${{ steps.get-tags.output }}
